In [1]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
        
    def forward(self,x,y):
        self.x = x
        self.y = y
        out = x*y
        
        return out
    
    def backward(self, dout):
        dx = dout*self.y
        dy = dout*self.x
        
        return dx, dy

In [2]:
apple=100
apple_num =2
tax =1.1

In [3]:
mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

In [4]:
apple_price = mul_apple_layer.forward(apple, apple_num)
price = mul_tax_layer.forward(apple_price,tax)

In [5]:
dprice = 1 #미분값이 1이 들어왔다면 계산 
dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple,dapple_num = mul_apple_layer.backward(dapple_price)

In [6]:
#개별적인 결과들이 나옴 
print("price:",int(price))
print("dApple:",dapple)
print("dApple_num:",int(dapple_num))
print("dTax:",dtax)

price: 220
dApple: 2.2
dApple_num: 110
dTax: 200


In [7]:
class AddLayer:
    def __init__(self):
        pass
    def forward(self,x,y):
        out = x+y
        
        return out
    
    def backward(self,dout): #backward 는 그냥 넘겨줌 
        dx = dout*1
        dy = dout*1
        
        return dx, dy

In [8]:
apple =100
apple_num =2
orange = 150
orange_num =3
tax =1.1

In [9]:
mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_tax_layer = MulLayer()

In [10]:
apple_price = mul_apple_layer.forward(apple,apple_num)
orange_price = mul_orange_layer.forward(orange,orange_num)
all_price = add_apple_orange_layer.forward(apple_price,orange_price)
price = mul_tax_layer.forward(all_price,tax)

In [11]:
dprice =1
dall_price, dtax = mul_tax_layer.backward(dprice)
dapple_price,dorange_price = add_apple_orange_layer.backward(dall_price)
dorange,dorange_num = mul_orange_layer.backward(dorange_price)
dapple,dapple_num = mul_apple_layer.backward(dapple_price)

In [12]:
print("price:",int(price))
print("dApple:",dapple)
print("dApple_num:",int(dapple_num))
print("dOrange_num:",int(dorange_num))
print("dTax:",dtax)

price: 715
dApple: 2.2
dApple_num: 110
dOrange_num: 165
dTax: 650


### 활성화 함수 구현 

#### relu 계층 구현하기 : x가 0보다 크면 역전파 상류의 값을 그대로 하류로 흘림/ x가 0이하면 역전파 때는 하류로 0을 보냄

In [13]:
class Relu:
    def __init__(self):
        self.mask =None #mask 는 True/False로 구성된 넘파이 배열 
        
    def forward(self,x):
        self.mask = (x <=0)
        out= x.copy
        out[self.mask] =0
        
    def backward(self,dout):
        dout[self.mask] =0
        dx = dout
        
        return dx

In [26]:
import numpy as np
x  = np.array([[1.0,-5.0],[-2.0,3.0]])
print(x)

[[ 1. -5.]
 [-2.  3.]]


In [31]:
mask=(x <=0)
print(mask)

[[False  True]
 [ True False]]


#### sigmoid 계층 구현하기

In [34]:
class Sigmoid:
    def __init__(self):
        self.out = None
    
    def forward(self,x):
        out =1/(1+np.exp(-x))
        self.out = out
        
        return out
    

    def backward(self,dout):
        dx = dout *(1.0 - self.out)*self.out
        
        return dx
    

In [48]:
X = np.random.rand(2) #입력
W = np.random.rand(2, 3) #가중치
B = np.random.rand(3) #편향

print(X.shape)
print(W.shape)
print(B.shape)


(2,)
(2, 3)
(3,)


In [36]:
Y = np.dot(X,W) +B
print(Y)

[1.16101882 1.0576344  0.98046046]


In [38]:
X_dot_W = np.array([[0,0,0],[10,10,10]]) 
B = np.array([1,2,3])

In [40]:
X_dot_W

array([[ 0,  0,  0],
       [10, 10, 10]])

In [41]:
X_dot_W +B

array([[ 1,  2,  3],
       [11, 12, 13]])

In [42]:
dY = np.array([[1,2,3],[4,5,6]])
dY               

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
dB = np.sum(dY,axis=0)
dB

array([5, 7, 9])

In [45]:
class Affine:
    def __init__(self,w,b):
        self.w =w
        self.b = b
        self.x = None
        self.dw = None
        self.db = None
        
    def forward(self, x):
        self.x =x
        out = np.dot(x,self.w) +self.b
        
        return out
    
    
    def backword(self,out):
        dx = np.dot(dout,self.W.T)
        self.dw = np.dot(self.W.T ,dout)
        self.db = np.sum(dout,axis=0)
        
        return dx